name: Unipot
version: "1.5"
license: "GPL-2.0-or-later"
date: 2022-02-22
description: |
    Computing with elements of unipotent subgroups of Chevalley groups

authors:
    - name: Sergei Haller
      url: http://www.sergei-haller.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/unipot/
readme: README.md
packageinfo: https://gap-packages.github.io/unipot/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/unipot/releases/download/v1.5/unipot-1.5.tar.gz

abstract: |
    Tools for computing with elements of unipotent subgroups of Chevalley groups.

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    Chevalley, unipotent elements, unipot.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HH22</span>]   <b class='BibAuthor'>Haller, S. and Horn, M.</b>,
     <i class='BibTitle'>Unipot, Computing with elements of unipotent subgroups of Chevalley groups,
             Version 1.5</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/unipot/">https://gap-packages.github.io/unipot/</a></span>.
    </p>
    

bibtex: |
    @misc{ Unipot1.5,
      author =           {Haller, S. and Horn, M.},
      title =            {{Unipot},   Computing   with   elements  of  unipotent
                          subgroups of Chevalley groups, {V}ersion 1.5},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/unipot/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{unipot/}}},
      keywords =         {Chevalley; unipotent elements; unipot},
      printedkey =       {HH22}
    }

