name: unipot
version: 1.2
date: 16/11/2004
description: |
    Computing with elements of unipotent subgroups of Chevalley groups

authors:
    - name: Sergei Haller
      url: http://www.sergei-haller.de

maintainers:
    - name: Sergei Haller
      url: http://www.sergei-haller.de

GAP: ">=4.4"

www: http://www.uni-giessen.de/~gc1007/unipot/
readme: README
packageinfo: http://www.uni-giessen.de/~gc1007/unipot/PackageInfo.g

downloads:
    - name: .tar.bz2
      url: http://www.uni-giessen.de/~gc1007/unipot/unipot-1.2.tar.bz2

abstract: |
    Tools for computing with elements of unipotent subgroups of Chevalley groups.

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
