name: Unipot
version: 1.4
date: 2018-04-09
description: |
    Computing with elements of unipotent subgroups of Chevalley groups

authors:
    - name: Sergei Haller
      url: http://www.sergei-haller.de

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/unipot/
readme: README.md
packageinfo: https://gap-packages.github.io/unipot/PackageInfo.g

downloads:
    - name: .tar.bz2
      url: https://github.com/gap-packages/unipot/releases/download/v1.4/unipot-1.4.tar.bz2

abstract: |
    Tools for computing with elements of unipotent subgroups of Chevalley groups.

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
